layout_spectrum: 0.7689136
typography_spectrum: 0.5533526
color:
  saturation: 0.1443826
  lightness: 0.5604351
  brandStrength: 0.2400631
  rhythmicContrast: 0.2611852
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
name: The Way the Truth
